// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HabitFlow.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class UpdateTargetModel : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "target_unit",
                schema: "habit_flow",
                table: "habits",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer",
                oldMaxLength: 100);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "target_unit",
                schema: "habit_flow",
                table: "habits",
                type: "integer",
                maxLength: 100,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(100)",
                oldMaxLength: 100);
        }
    }
}
